variables:
    IMAGE_NAME: oraikevich/python-app
    IMAGE_TAG: expense-tracker-telegram-bot

build_telegram_bot:
  image: python:3.9-slim-buster
  before_script:
    apt-get update && apt-get install make
  script:
    - make start

build_image:
  image: docker:27.2.0-cli
  sevices:
    - docker:27.2.0-dind
  variables:
    - DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG