variables:
    IMAGE_NAME: olegraikevich/python-app
    IMAGE_TAG: expense-tracker-telegram-bot

stages:
  - build
  - deploy

build_image:
  stage: build
  image: docker:27.2.0-cli
  services:
    - docker:27.2.0-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY root@64.227.114.129 "
      docker login -u $DOCKER_USER -p $DOCKER_PASSWORD &&
      docker run -d -e TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN -p 5000:5000 $IMAGE_NAME:$IMAGE_TAG"      

